### ISSUE TITLE
SIGSEV error during parsing html

### ISSUE THREAD

**Issue by ReyPJ** [tree-sitter/tree-sitter-html#101]
So I was using nvim without problems but when I opened a HTML file neovim crash, I ran a coredumpctl, and the backtrace indicates that the error occurred during a memory free operation, related to the external scanner of Tree-sitter for HTML, I already try to uninstall and reinstall the parser and in :checkhealt nvim-treesitter the HTML parser is OK

checkheatl outpo:

`nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v22.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.1.1 20240522
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.6.32-1-MANJARO",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Mon May 27 03:41:25 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - gitignore           ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - htmldjango          ✓ . ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - tmux                ✓ . . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~`
         
         
         
I already uninstall de parser and installed it again

**Comment by amaanq** [comment]
guaranteed you're using an older parser version, *ensure* you're using it built from the latest version

**Comment by TarunDaCoder** [comment]
Hey, I have also encountered this error, but when I do `:TSUpdate` it shows `All parsers are up-to-date!`

**Comment by muriware** [comment]
@amaanq, I'm running into the same issue.

`:TSUpdate html` shows that `Parsers are up-to-date!`

When it crashes, it prints on the screen:

`nvim(77752,0x119e07600) malloc: *** error for object 0x6d69766f656e2f72: pointer being freed was not allocated`
`nvim(77752,0x119e07600) malloc: *** set a breakpoint in malloc_error_break to debug`

It only happens with the HTML parser installed.

When the parser is uninstalled, nvim no longer crashes on HTML files.

**Comment by TarunDaCoder** [comment]
> @amaanq, I'm running into the same issue.
> 
> `:TSUpdate html` shows that `Parsers are up-to-date!`
> 
> When it crashes, it prints on the screen:
> 
> `nvim(77752,0x119e07600) malloc: *** error for object 0x6d69766f656e2f72: pointer being freed was not allocated` `nvim(77752,0x119e07600) malloc: *** set a breakpoint in malloc_error_break to debug`
> 
> It only happens with the HTML parser installed.
> 
> When the parser is uninstalled, nvim no longer crashes on HTML files.

I solved this by building the HTML parser from source

**Comment by muriware** [comment]
@TarunDaCoder, I caught that from your open issue [#6730](https://github.com/nvim-treesitter/nvim-treesitter/issues/6730#issuecomment-2150490334) on nvim-treesitter.

I think a better solution would be to delete the entire nvim cache directory, as this issue could have been caused by corrupted nvim cache files. Then reinstall all plugins, and allow nvim to recreate any necessary cache files when it runs.
