### ISSUE TITLE
`pre` tag inside a `p` tag produces an error

### ISSUE THREAD

**Issue by stsewd** [tree-sitter/tree-sitter-html#105]
The following HTML isn't parsed correctly.

```html
<p><pre></pre></p>
```

It produces the following tree

```
document [0, 0] - [1, 0]
  element [0, 0] - [0, 3]
    start_tag [0, 0] - [0, 3]
      tag_name [0, 1] - [0, 2]
  element [0, 3] - [0, 14]
    start_tag [0, 3] - [0, 8]
      tag_name [0, 4] - [0, 7]
    end_tag [0, 8] - [0, 14]
      tag_name [0, 10] - [0, 13]
  ERROR [0, 14] - [0, 18]
    ERROR [0, 16] - [0, 17]
```

**Comment by ghedwards** [comment]
https://github.com/tree-sitter/tree-sitter-html/blob/master/src/tag.h has pre listed in TAG_TYPES_NOT_ALLOWED_IN_PARAGRAPHS , is this correct ? is it invalid to do this ?

**Comment by stsewd** [comment]
Oh, that's correct, pre tags can't be inside p tags. I saw a warning in the browser as well.
