### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by JordanAnthonyKing** [tree-sitter/tree-sitter-html#106]
I notice Emacs now includes an html-ts-mode. Does it replace this project?

**Comment by ObserverOfTime** [comment]
It uses this project.

**Comment by JordanAnthonyKing** [comment]
Weird, when I looked at the source file it didn’t line up.

**Comment by ghedwards** [comment]
tree-sitter-html is a dependency ( not a fork ) of the "html-ts-mode" as are other "ts-modes" for Emacs
