### ISSUE TITLE
Parser crashes neovim

### ISSUE THREAD

**Issue by dominicmeyer** [tree-sitter/tree-sitter-html#110]
Hi, I've got an issue where this Parser crashes my neovim all the time.
When opening a html file like so:

```html
<!doctype html>
<html lang="en">

<body></body>

</html>
```

And trying to type in h1 like so:

```html
<!doctype html>
<html lang="en">

<body>h1</body>

</html>
```

My neovim crashes everytime when the 1 is hit on the keyboard.
When the Parser is not installed, this doesn't happen.

I actually don't now where the logs from treesitter are stored, if you need extra logs or anything else please tell me.

Neovim Version: v0.10.1
Build type: Release
LuaJIT 2.1.1713484068

**Comment by amaanq** [comment]
1) This is *just* the parser repo. Crashes need to be reproducible w/ tree-sitter alone to be valid here
2) You're using a *very* outdated parser version which causes these crashes.
