### ISSUE TITLE
Error syntax html

### ISSUE THREAD

**Issue by thevan96** [tree-sitter/tree-sitter-html#26]
- Why is there a line?
![Screen Shot 2021-04-02 at 8 10 57 PM](https://user-images.githubusercontent.com/47932916/113418363-8a330b80-93ef-11eb-81ad-ba1352e61575.png)

**Comment by maxbrunsfeld** [comment]
Did you mean to open this issue on neovim or some other repo?

**Comment by thevan96** [comment]
Just in repo tree-sitter-html

**Comment by maxbrunsfeld** [comment]
This repo contains a grammar; UI elements in a text editor are handled by other layers of logic.

**Comment by thevan96** [comment]
I don't know. Thank answer.
