### ISSUE TITLE
Request: make WASM file available to download

### ISSUE THREAD

**Issue by gushogg-blake** [tree-sitter/tree-sitter-html#28]
It would be great if there was a wasm file to download as in https://github.com/tree-sitter/tree-sitter-javascript.  I've tried building my own but got errors (first bad magic number, then `Cannot read property 'apply' of undefined` from tree-sitter).  Having it in a central place would also mean we could see which version of tree-sitter it has been compiled against.

**Comment by milahu** [comment]
quickfix:
use wasm from https://tree-sitter.github.io/tree-sitter/7-playground.html

https://tree-sitter.github.io/tree-sitter-html.wasm
https://tree-sitter.github.io/tree-sitter-c.wasm
https://tree-sitter.github.io/tree-sitter-c_sharp.wasm
...

**Comment by amaanq** [comment]
not planned to check in wasm files in the repo - down the line we will release them as an artifact on gh releases, but for now wasm should build w/o any issues because the scanner no longer uses c++
