### ISSUE TITLE
HTML synax highlighting won't work properly

### ISSUE THREAD

**Issue by JS-junky** [tree-sitter/tree-sitter-html#32]
well as you can see some of the html seem to loose their syntax highlighting and turn plain white!
this occurs all the time, when opening an html file, when writing an html file... heck even sometimes when moving my cursor to a tag it just suddenly looses its highlighting!
![Screenshot_20210905_154542](https://user-images.githubusercontent.com/68812862/132124800-07f06926-0793-402a-abda-dcbb759536da.png)

**Comment by efierros** [comment]
@JS-junky Why did you closed this issue? Did you solve it? Could you please share the fix? I'm having the same issue on plain html.

**Comment by JS-junky** [comment]
> @JS-junky Why did you closed this issue? Did you solve it? Could you please share the fix? I'm having the same issue on plain html.
> 
> 

well i also posted the same issue on the main nvim-treesitter repo and they said they'll be working on it on the next upstream version of neovim... so that's why close it.

**Comment by JS-junky** [comment]
also my issue is not specific to just one html file... it's every html file no matter how big the file is

**Comment by efierros** [comment]
Just like me, thanks, gonna check the main repo and wait for the solution.
