### ISSUE TITLE
Embed regexp in pattern attribute on input elements

### ISSUE THREAD

**Issue by bennypowers** [tree-sitter/tree-sitter-html#37]
Would be great to break into regexp parsing in the `pattern` attribute IFF the tag name is input

<img width="880" alt="Screen Shot 2022-02-23 at 23 53 56" src="https://user-images.githubusercontent.com/1466420/155460413-85c153bc-c819-41b3-a66c-c73e6482c5fa.png">

**Comment by maxbrunsfeld** [comment]
That makes sense! Note that if you're using Neovim, it does its own injection queries, so it would control that regex injection, not this repo.
