### ISSUE TITLE
BUG 🐞: parsing breaks when using framework attribute tags such as `@class('test')` 

### ISSUE THREAD

**Issue by EmranMR** [tree-sitter/tree-sitter-html#65]
Hello 👋

There is a bug with `tree-sitter-html` when parsing a tag containing an unconventional attributes provided by web frameworks.

For example in Laravel users, use `@class()` [in the attribute region](https://laravel.com/docs/10.x/blade#conditional-classes). However when this is used this will causes breakage. I played around a bit, seems to be an issue with the closing `)` preceding the next attribute.

You can even see this in Github's syntax highlighting as below: 👇

```HTML
<div id="test" class="test"></div>
vs
<div  @class('test') slot="test" class="test"></div>
```

Also see [Laravel Nova Extension#11](https://github.com/EmranMR/Laravel-Nova-Extension/issues/11#issue-1861715618) for more example/screenshots.

Thanks
Emran

**Comment by amaanq** [comment]
laravel isn't html though, a grammar for that should be built on top of html

**Comment by EmranMR** [comment]
@amaanq Mmmm 🤔 you are right!  after investigating more, it does not seem to be an issue with `tree-sitter-html`. It also doesn't seem to be related to the `)`. 😬

It seems to be an injection issue and a conflict with the spaces, resulting  in`tag name` and `attribute name` merging into one and parsed as  a `tag name`, followed by a `=` hence the error.

I will close this issue and move it to [tree-sitter-blade](https://github.com/EmranMR/tree-sitter-blade). Sorry for the confusion, there are just too many layers of injections and sometimes confusing to debug!  `blade->php->html` 😩

**Comment by amaanq** [comment]
yeah injections can get finnicky when it comes to languages inside a language containing blobs of the parent language
