### ISSUE TITLE
Publish 0.20.0

### ISSUE THREAD

**Issue by cloudhead** [tree-sitter/tree-sitter-html#68]
Hey there, when you get a chance, could you publish 0.20.0 to crates.io? The scanner rewrite in C is essential for us! Thanks.

**Comment by dlvandenberg** [comment]
@amaanq Can you publish this?

**Comment by clason** [comment]
This release is missing a tag, too.

**Comment by dlvandenberg** [comment]
The problem is, [this guy](https://github.com/sergey-sign) is the owner of the crate on crates.io..

**Comment by cloudhead** [comment]
@sergey-sign do you mind publishing a new version, or handing over crate ownership?

**Comment by sergey-sign** [comment]
Sorry, I published it.
who should I add to the owners so that such situations do not arise?

**Comment by cloudhead** [comment]
Thanks! Maybe @maxbrunsfeld ?

**Comment by amaanq** [comment]
Yeah, Max (maxbrunsfeld@gmail.com) having access would be great and will enable me to publish to it.

**Comment by amaanq** [comment]
ping @sergey-sign it'd be nice to give me (amaanq12@gmail.com) or Max (maxbrunsfeld@gmail.com) owner perms on crates...

**Comment by maxbrunsfeld** [comment]
Thanks so much for taking care of that @amaanq

**Comment by amaanq** [comment]
new release on crates is out
