### ISSUE TITLE
Parser failure on unclosed <head> inside unclosed <html>

### ISSUE THREAD

**Issue by clarfonthey** [tree-sitter/tree-sitter-html#75]
Hello, I ran into this issue with difftastic and managed to trace it back to this parser. After narrowing down the HTML that was failing to parse, I managed this:

```html
<!doctype html><html><head>
```

Essentially, instead of being labelled as an implicitly closed element inside an implicitly closed element, it's labelled as an error with two start tags.

This feels undesirable, considering how a missing `</head>`, `</body>`, or `</html>` will cause the entire document (or half of it) to be enclosed in an error node, which breaks the parsing of the individual parts.

**Comment by milahu** [comment]
> implicitly closed element

i guess youre confusing this with `<img>` and `<br>` and `<hr>` and ...

in other words, youre looking for a fault-tolerant html parser as used by web browsers
imo this is out of scope for tree-sitter-html

see also [How do browsers deal with malformed HTML?](https://stackoverflow.com/questions/8359532/how-do-browsers-deal-with-malformed-html)

**Comment by clarfonthey** [comment]
This isn't malformed HTML; it's listed explicitly in the spec:
* https://html.spec.whatwg.org/multipage/semantics.html#the-html-element
* https://html.spec.whatwg.org/multipage/semantics.html#the-head-element
* https://html.spec.whatwg.org/multipage/sections.html#the-body-element

The end tags for `html`, `head`, and `body` can all be omitted in valid HTML.

**Comment by clarfonthey** [comment]
Small note, but this isn't 100% fixed; you can also implicitly close a `<head>` or `<body>` element by adding the other (not just by EOF), and this isn't accounted for in #84. In other words, this doesn't work:

```html
<!DOCTYPE><html><head><body>
```

The specific wording of "ASCII whitespace" and "comment" is used to detail the way that content is inferred to be in either the head or body if the end (or start!) tags are missing. Basically, there are two:

1. Comments are just inferred to be in the tag that was most recently opened, so, if you want to explicitly include them in either the head or body, you need an explicit tag.
2. ASCII whitespace has a different interpretation in the head and body, where it's ignored in the head, but treated as a text node in the body. The default interpretation is that any leading ASCII whitespace is treated as part of the `<head>` unless you explicitly close it and make it part of the body.

By these rules, you can explicitly omit the head and body altogether and it'll interpret what is what based upon where the tags are usually located, but you can also choose to simply omit the `</head>` and use `<body>` to end the head, since it's well-understood that the `<html>` tag just contains a head and body, in that order.

I included the `<html><head>` example since that was the simplest one, but technically there should also be a `<html><head><body>` test as well to indicate the body too. And perhaps a few other simple examples, like:

* `<!DOCTYPE><html><meta><p>`:
```
(document (doctype)
  (element
    (start_tag (tag_name))
  (element
    (start_tag (tag_name)))
```
* `<!DOCTYPE><html><head><meta><p>`:
```
(document (doctype)
  (element
    (element
      (start_tag (tag_name)))
  (element
    (start_tag (tag_name)))
```
* `<!DOCTYPE><html><meta><body><p>`
```
(document (doctype)
  (element
    (start_tag (tag_name))
  (element
    (element
      (start_tag (tag_name))))
```
* `<!DOCTYPE><html><head><meta><body><p>`
```
(document (doctype)
  (element
    (element
      (start_tag (tag_name)))
  (element
    (element
      (start_tag (tag_name))))
```

I don't think that tree-sitter needs to explicitly sort the tags into a head and body (it's fine with other elements inside `<html>` directly) but I think that it should be able to implicitly close a `</head>` tag based upon the presence of body elements. Right now, it just complains still about the main case, which is a `<head>` being implicitly closed by a `<body>`.
