### ISSUE TITLE
Is it possible to have this parser support nested HTML comments?

### ISSUE THREAD

**Issue by ghedwards** [tree-sitter/tree-sitter-html#76]
Is it possible to have this parser support nested HTML comments?

`
-->`

**Comment by amaanq** [comment]
That's not valid, is it?

**Comment by ghedwards** [comment]
Not sure, browsers tend to be quite forgiving even if the spec says it's not "valid" I'm sure people out there are doing it, I have a version for cfml comments counting the open / close comments, super early days on that project though

**Comment by amaanq** [comment]
idk, I'd think cfml is deserving of its own grammar (maybe built on top of this? idk cfml at all), and it's invalid in html so I'd like to say we probably won't implement it here..

**Comment by ghedwards** [comment]
I've made a start, its pretty rough and not using appropriate naming conventions yet, https://github.com/cfmleditor/tree-sitter-cfml but I might keep chipping away at it
