### ISSUE TITLE
xhtml: allow xml processing instructions <?xml ... ?>

### ISSUE THREAD

**Issue by milahu** [tree-sitter/tree-sitter-html#82]
currently xml processing instruction gives a parse error

```xml
<?xml version="1.0" encoding="UTF-8"?>
```

[lezer-parser-html](https://github.com/lezer-parser/html) supports this

or is this out of scope for tree-sitter-html
and should be handled by tree-sitter-xml?

xhtml example

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<body>asdf</body>
</html>
```

**Comment by amaanq** [comment]
check out https://github.com/tree-sitter-grammars/tree-sitter-xml

**Comment by milahu** [comment]
ok, so xhtml is

> out of scope for tree-sitter-html

**Comment by amaanq** [comment]
yeah sorry I should've specified that
