### ISSUE TITLE
"</script>" string literal in javascript breaks parser?

### ISSUE THREAD

**Issue by michaelfortunato** [tree-sitter/tree-sitter-html#86]
<img width="2560" alt="image" src="https://github.com/tree-sitter/tree-sitter-html/assets/43207799/2342185a-c5a8-4437-b7af-3e35ebb10f5d">

I was looking at scan_raw_text and it seems like it does not account for string literals. 

```ascii
<html>
<script>
const a = "</script>"
const b = ""
</script>
</html>
```

```
Leads to this syntax tree: 
[fragment](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [6, 0]
  [element](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [5, 7]
    [start_tag](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [0, 6]
      [tag_name](https://tree-sitter.github.io/tree-sitter/playground#) [0, 1] - [0, 5]
    [script_element](https://tree-sitter.github.io/tree-sitter/playground#) [1, 0] - [2, 20]
      [start_tag](https://tree-sitter.github.io/tree-sitter/playground#) [1, 0] - [1, 8]
        [tag_name](https://tree-sitter.github.io/tree-sitter/playground#) [1, 1] - [1, 7]
      [raw_text](https://tree-sitter.github.io/tree-sitter/playground#) [1, 8] - [2, 11]
      [end_tag](https://tree-sitter.github.io/tree-sitter/playground#) [2, 11] - [2, 20]
        [tag_name](https://tree-sitter.github.io/tree-sitter/playground#) [2, 13] - [2, 19]
    [text](https://tree-sitter.github.io/tree-sitter/playground#) [2, 20] - [3, 12]
    [erroneous_end_tag](https://tree-sitter.github.io/tree-sitter/playground#) [4, 0] - [4, 9]
      [erroneous_end_tag_name](https://tree-sitter.github.io/tree-sitter/playground#) [4, 2] - [4, 8]
    [end_tag](https://tree-sitter.github.io/tree-sitter/playground#) [5, 0] - [5, 7]
      [tag_name](https://tree-sitter.github.io/tree-sitter/playground#) [5, 2] - [5, 6]
```
In fact we can see the highlighter break here. 
```html
<html>
<script>
const a = "</script>"
const b = ""
</script>
</html>
```

Would a PR, where " and ` are checked and balanced in scan_raw_text be a good fix this issue?  This would only apply when scan_raw_text is expecting a "</script>" tag.

**Comment by michaelfortunato** [comment]
I think the following rules might be able to handle the raw_text rule in the case of <script> tags only
```javascript
method_body: $ => seq("{", repeat($.method_body_content), "}"),
method_body_content: $ => choice(/[^"}]+/, $.string_literal),
string_literal: $ => seq("\"", repeat(choice((/[^"]+/), token.immediate("\"\""))), "\""),
```

**Comment by maxbrunsfeld** [comment]
Isn't this the correct behavior? Can you test with a web browser and an actual HTML document?

**Comment by milahu** [comment]
> I wonder if html <script> was designed this way intentionally.

yes, this is intentional

html is the host language, javascript is the guest language
so html needs to know the script end without parsing the script

see also https://github.com/tree-sitter/tree-sitter/issues/121

> this is the behavior that is needed for processing these kinds of nested languages correctly. We don't want the child language (JavaScript) to have any influence over when the nested document ends; that is controlled by the parent language HTML. We need that information before calling into the JavaScript parser.

> Perhaps some languages are designed to hand control over to the child parser for segments like that, in which case the approach is sound. But in the majority of cases, it is the parent parser that knows when the scope ends, not the child, because the entire concept of being in some kind of sub-language scope is handled by the parent, while the child doesn't know it's only a snippet of a larger document.
