### ISSUE TITLE
Segmentation fault in neovim with neovim-treesitter

### ISSUE THREAD

**Issue by jacekjarosz55** [tree-sitter/tree-sitter-html#94]
Only happens with the html parser from what i see,
on latest arch linux (6.8.5-arch1-1  SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:33 +0000 x86_64 GNU/Linux)

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `nvim --embed index.html'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000706e1d2e2e3e in free () from /usr/lib/libc.so.6
```

**Comment by jacekjarosz55** [comment]
Whoops, sorry, neovim-treesitter has updated and the issue is no longer present

**Comment by nwalkewicz** [comment]
@jacekjarosz55 Thank you for this, I was having the same problem until I updated treesitter.
